version: "3"

services:
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app-frontend
    depends_on:
      - backend
    container_name: delivery_front
  backend:
    build: ./back-end
    container_name: delivery_api
    tty: true
    stdin_open: true
    command: bash
    restart: always
    volumes: 
      - ./back-end:/app-backend
    depends_on:
      - db
    ports:
      - 3001:3001
  db:
    container_name: delivery_db
    image: mysql:8.0.21
    environment:
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always