version: "3"

services:
  frontend:
    build: ./front-end
    ports:
      - 3000:3000
    platform: linux/x86_64
    working_dir: /app/frontend
    depends_on:
      - backend
    container_name: delivery_front
  backend:
    build: ./back-end
    working_dir: /app/backend
    volumes:
      - ./back-end:/app/backend
    container_name: delivery_api
    tty: true
    stdin_open: true
    command: npm run db:reset
    restart: always
    depends_on:
      - db
    ports:
      - 3001:3001
    environment:
      - NODE_ENV=development
      - API_PORT=3001
      - MYSQL_HOST=delivery_db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DB_NAME=delivery-app
      - EVAL_ALWAYS_RESTORE_DEV_DB=true
  db:
    container_name: delivery_db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password

networks:
  default:
    name: app-delivery_net